### ISSUE TITLE
WHO???

### ISSUE THREAD

**Issue by amongusenjoyer69** [AnkerFung/Skligga-Hack#1]
Anker NN CODER dog shit client why waste time for larp? Probably just copy paste reupload jar.Why anyonenbother to look at client when dev 0 reputation? Major issue inclient: just noob and waste time. NN. What is saligaud jack? What can it even do? Bad repo terrible repo only gives building info wow id rather use WUTST PLUS 2 LOL!!!! TransgenderWkman in shambles

**Comment by AnkerFung** [comment]
talk shit on ur main
