### ISSUE TITLE
WTF MAN

### ISSUE THREAD

**Issue by TheFirstPlaceCoder** [AnkerFung/Skligga-Hack#6]
WTF IS THIS BRUH. ANOTHER SHIT CLIENT FOR "VANILLA CPVPERS"
This is cheat lol, but u say that its modification, bruh

USE NORMAL CLIENT — https://meteorclient.com/ but not ur shit

**Comment by pythoniccodeing** [comment]
Mad? Meteor dosent have modules that vanilla cpvpers would need

**Comment by TheFirstPlaceCoder** [comment]
AHAHAHAHAHAHAHAAH LMAO, METEOR IS THE BEST CLIENT. IT HAS ALL THAT YOU NEED BRUH

**Comment by TheFirstPlaceCoder** [comment]
Just u cant get configs for meteor and crying(((

**Comment by nullablepointer** [comment]
Cry bout using this shit + this is ghost client for a reason. Its not hvh
